// <auto-generated />
using System;
using ContentProcessing.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContentProcessing.Persistence.Migrations
{
    [DbContext(typeof(ContentProcessingDbContext))]
    [Migration("20260417132138_RemovePdfToImagesStatus")]
    partial class RemovePdfToImagesStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContentProcessing.Persistence.Entities.App.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_path");

                    b.Property<string>("ImageSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("image_sha256")
                        .IsFixedLength();

                    b.Property<int>("PageNumber")
                        .HasColumnType("integer")
                        .HasColumnName("page_number");

                    b.Property<Guid>("PdfToImagesId")
                        .HasColumnType("uuid")
                        .HasColumnName("pdf_to_images_id");

                    b.HasKey("Id")
                        .HasName("pk_images");

                    b.HasIndex("PdfToImagesId")
                        .HasDatabaseName("idx_images_pdf_to_images_id");

                    b.ToTable("images", "app", t =>
                        {
                            t.HasCheckConstraint("CK_images_image_sha256", "octet_length(trim(image_sha256::text)) = 64 AND trim(image_sha256::text) ~ '^[0-9a-fA-F]{64}$'");

                            t.HasCheckConstraint("CK_images_page_number", "page_number >= 0");
                        });
                });

            modelBuilder.Entity("ContentProcessing.Persistence.Entities.App.PdfToImages", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<Guid?>("FirstPageImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("first_page_image_id");

                    b.Property<string>("PdfPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pdf_path");

                    b.Property<string>("PdfSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("pdf_sha256")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_pdf_to_images");

                    b.HasIndex("FirstPageImageId")
                        .HasDatabaseName("ix_pdf_to_images_first_page_image_id");

                    b.ToTable("pdf_to_images", "app", t =>
                        {
                            t.HasCheckConstraint("CK_pdf_to_images_pdf_sha256", "octet_length(trim(pdf_sha256::text)) = 64 AND trim(pdf_sha256::text) ~ '^[0-9a-fA-F]{64}$'");
                        });
                });

            modelBuilder.Entity("ContentProcessing.Persistence.Entities.Auth.ApiKey", b =>
                {
                    b.Property<Guid>("ApiKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("api_key_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.PrimitiveCollection<string[]>("Scopes")
                        .HasColumnType("text[]")
                        .HasColumnName("scopes");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("secret_hash")
                        .IsFixedLength();

                    b.HasKey("ApiKeyId")
                        .HasName("pk_api_keys");

                    b.ToTable("api_keys", "auth", t =>
                        {
                            t.HasCheckConstraint("ck_api_keys_scopes", "scopes IS NULL OR scopes <@ ARRAY['content:read', 'content:write', 'iam:admin']::text[]");

                            t.HasCheckConstraint("ck_api_keys_secret", "octet_length(trim(secret_hash::text)) = 64 AND trim(secret_hash::text) ~ '^[0-9a-fA-F]{64}$'");
                        });
                });

            modelBuilder.Entity("ContentProcessing.Persistence.Entities.App.Image", b =>
                {
                    b.HasOne("ContentProcessing.Persistence.Entities.App.PdfToImages", "PdfToImages")
                        .WithMany("Images")
                        .HasForeignKey("PdfToImagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_images_pdf_to_images_id");

                    b.Navigation("PdfToImages");
                });

            modelBuilder.Entity("ContentProcessing.Persistence.Entities.App.PdfToImages", b =>
                {
                    b.HasOne("ContentProcessing.Persistence.Entities.App.Image", "FirstPageImage")
                        .WithMany()
                        .HasForeignKey("FirstPageImageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_pdf_to_images_first_page_image_id");

                    b.Navigation("FirstPageImage");
                });

            modelBuilder.Entity("ContentProcessing.Persistence.Entities.App.PdfToImages", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
