"""add_order_and_expedition_to_viber_jobs

Revision ID: 666b23e2842d
Revises: 1bf52336a762
Create Date: 2026-09-23 16:33:53.243078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '666b23e2842d'
down_revision: Union[str, Sequence[str], None] = '1bf52336a762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viber_jobs', sa.Column('dfd_order_number', sa.Text(), nullable=False), schema='app')
    op.add_column('viber_jobs', sa.Column('expedition_date', sa.Date(), nullable=False), schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viber_jobs', 'expedition_date', schema='app')
    op.drop_column('viber_jobs', 'dfd_order_number', schema='app')
    # ### end Alembic commands ###
