"""adjust_viber_job_fields

Revision ID: 8f4cc961c4e2
Revises: 666b23e2842d
Create Date: 2026-09-28 15:37:33.519009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f4cc961c4e2'
down_revision: Union[str, Sequence[str], None] = '666b23e2842d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viber_jobs', sa.Column('customer_order_number', sa.String(length=32), nullable=False), schema='app')
    op.alter_column('viber_jobs', 'plate_size',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False,
               schema='app')
    op.alter_column('viber_jobs', 'plate_sign',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False,
               schema='app')
    op.alter_column('viber_jobs', 'dfd_order_number',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False,
               schema='app')
    op.alter_column('viber_jobs', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"),
               schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('viber_jobs', 'status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"),
               schema='app')
    op.alter_column('viber_jobs', 'dfd_order_number',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False,
               schema='app')
    op.alter_column('viber_jobs', 'plate_sign',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False,
               schema='app')
    op.alter_column('viber_jobs', 'plate_size',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False,
               schema='app')
    op.drop_column('viber_jobs', 'customer_order_number', schema='app')
    # ### end Alembic commands ###
