name: Deploy - Production

on:
  push:
    branches: ["main"]

concurrency:
  group: deploy-production
  cancel-in-progress: false

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: production
      env_root: 'D:\services\content-processing\prod'
      flyway_env: prod
      winsw_suffix: Prod
      health_port_base: 8080