name: Deploy - Staging

on:
  push:
    branches: ["staging"]

concurrency:
  group: deploy-staging
  cancel-in-progress: false

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: staging
      env_root: 'D:\services\content-processing\staging'
      flyway_env: staging
      winsw_suffix: Staging
      health_port_base: 9080